<?php

// Callback function for the main landing page
function gatekeeper_usage_activities_page() {
    ?>
    <div class="wrap">
    <h1>GateKeeper - Usage and Activities</h1>

    <h2>Latest Invited Users</h2>
    <table class="widefat">
        <thead>
            <tr>
                <th>User ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Invite Status</th>
            </tr>
        </thead>
        <tbody>
            <?php
            // Retrieve and display the latest invited users here
            $latest_invited_users = get_latest_invited_users(); // Implement this function to fetch data
            foreach ($latest_invited_users as $user) {
                echo '<tr>';
                echo '<td>' . esc_html($user->ID) . '</td>';
                echo '<td>' . esc_html($user->user_login) . '</td>';
                echo '<td>' . esc_html($user->user_email) . '</td>';
                echo '<td>' . get_invite_status($user->ID) . '</td>'; // Implement this function to get invite status
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>

    <h2>Latest Generated Invite Keys</h2>
    <table class="widefat">
        <thead>
            <tr>
                <th>Invite Key</th>
                <th>Generated By</th>
                <th>Date Generated</th>
            </tr>
        </thead>
        <tbody>
            <?php
            // Retrieve and display the latest generated invite keys here
            $latest_generated_keys = get_latest_generated_keys(); // Implement this function to fetch data
            foreach ($latest_generated_keys as $key) {
                echo '<tr>';
                echo '<td>' . esc_html($key->invite_key) . '</td>';
                echo '<td>' . esc_html($key->generated_by) . '</td>';
                echo '<td>' . esc_html($key->date_generated) . '</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>

    <h2>Available Roles and Permissions</h2>
    <table class="widefat">
        <thead>
            <tr>
                <th>Role</th>
                <th>Capabilities</th>
            </tr>
        </thead>
        <tbody>
            <?php
            // Retrieve and display available roles and permissions here
            $available_roles = get_available_roles(); // Implement this function to fetch data
            foreach ($available_roles as $role => $capabilities) {
                echo '<tr>';
                echo '<td>' . esc_html($role) . '</td>';
                echo '<td>' . esc_html(implode(', ', $capabilities)) . '</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>
</div>
<?php } ?>